CREATE TABLE DEPT1(
    empid INT PRIMARY KEY NOT NULL,
    name VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE DEPT2(
    empid INT PRIMARY KEY NOT NULL,
    name VARCHAR(255),
    role VARCHAR(255)
)

-- union

SELECT * FROM DEPT1
UNION
SELECT * FROM DEPT2;

-- INTERSECT

SELECT DEPT1.* FROM DEPT1 INNER JOIN DEPT2 USING(empID);

--MINUS

SELECT DEPT1.* FROM DEPT1 LEFT JOIN DEPT2 USING(empID) WHERE DEPT2.empID = NULL;